version: "3"
services:
  instabotlol:
    env_file:
    - bot-variables.env
    restart: never
    image: gcr.io/instagrambot-273500/github.com/denovopress/instabotlol:latest
    ports:
      #instabot healthz
      - "81:8000"

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 120

  portainer:
    image: portainer/portainer
    restart: unless-stopped
    ports:
      #portainer web UI
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    env_file:
    - bot-variables.env
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      #Actual HTTP{S} Ports
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; /opt/nginx/reload_nginx.sh; done & /opt/nginx/run_nginx.sh'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    env_file:
    - bot-variables.env
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  portainer_data:
