version: "3"
services:
  instabotlol:
    env_file:
    - bot-variables.env
    image: gcr.io/instagrambot-273500/github.com/denovopress/instabotlol:latest
    ports:
      - "81:8000"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

  portainer:
    image: portainer/portainer
    ports:
      - "80:9000"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
